#!/bin/bash
usage () {
    printf "load-scenario [-h] home_dir [SCENARIO_FILE]\n"
}
while getopts "h" opt; do
  case $opt in
    h | [?]) usage ; exit;;
  esac
done
shift "$(($OPTIND -1))"
scenario_file=$2
if [ -z "$scenario_file" ]; then
	scenario_file="scenario.json"
fi

home_dir=$1
scenario_file=$home_dir/$scenario_file
scripts=/home/api/practiques/PA2/files/

routers_json_dir=$home_dir/$(jq -r '.routersJSONDir' $scenario_file)
hosts_json_dir=$home_dir/$(jq -r '.hostsJSONDir' $scenario_file)
routers_conf_dir=$home_dir/$(jq -r '.routersConfDir' $scenario_file)
hosts_conf_dir=$home_dir/$(jq -r '.hostsConfDir' $scenario_file)

$scripts/routers-conf -i $routers_json_dir -o $routers_conf_dir
$scripts/hosts-conf -i $hosts_json_dir -o $hosts_conf_dir
