#!/bin/bash
num_pcs=8
num_routers=12
num_bridges=27

count_dirs () {
    dir=$1   
    regexp=$2
    wc -l < <( awk '{print $NF}' < <(ls -l $dir) | grep -P $regexp )
}
routers=$(count_dirs "/var/lib/lxc/" "^R[0-9]{2}$")
pcs=$(count_dirs "/var/lib/lxc/" "^PC[0-9]{2}$")
dir=$1


for ((i=1; i<=$num_routers; i++)); do
    cp $dir/scripts/mroute /var/lib/lxc/$(printf "R%02d" $i)/rootfs/usr/local/bin   
    cp $dir/scripts/pimd /var/lib/lxc/$(printf "R%02d" $i)/rootfs/usr/local/sbin
    cp $dir/scripts/90-disable-rp_filter.conf /var/lib/lxc/$(printf "R%02d" $i)/rootfs/etc/sysctl.d
    lxc-attach -n $(printf "R%02d" $i) -- sysctl -w net.ipv4.conf.all.rp_filter=0
    lxc-attach -n $(printf "R%02d" $i) -- sysctl -w net.ipv4.conf.default.rp_filter=0
    lxc-attach -n $(printf "R%02d" $i) -- sysctl -w net.ipv4.conf.lo.rp_filter=0
    lxc-attach -n $(printf "R%02d" $i) -- ip link show | grep -q eth0 && lxc-attach -n $(printf "R%02d" $i) -- sysctl -w net.ipv4.conf.eth0.rp_filter=0
    lxc-attach -n $(printf "R%02d" $i) -- ip link show | grep -q eth1 && lxc-attach -n $(printf "R%02d" $i) -- sysctl -w net.ipv4.conf.eth1.rp_filter=0
    lxc-attach -n $(printf "R%02d" $i) -- ip link show | grep -q eth2 && lxc-attach -n $(printf "R%02d" $i) -- sysctl -w net.ipv4.conf.eth2.rp_filter=0
    lxc-attach -n $(printf "R%02d" $i) -- ip link show | grep -q eth3 && lxc-attach -n $(printf "R%02d" $i) -- sysctl -w net.ipv4.conf.eth3.rp_filter=0
    lxc-attach -n $(printf "R%02d" $i) -- ip link show | grep -q eth4 && lxc-attach -n $(printf "R%02d" $i) -- sysctl -w net.ipv4.conf.eth4.rp_filter=0
done
for ((i=1; i<=$num_pcs; i++)); do
    mkdir -p /var/lib/lxc/$(printf "PC%02d" $i)/rootfs/home/mgen
    cp $dir/config-pim/file_mgen_receiver /var/lib/lxc/$(printf "PC%02d" $i)/rootfs/home/mgen
    cp $dir/config-pim/file_mgen_source_11 /var/lib/lxc/$(printf "PC%02d" $i)/rootfs/home/mgen
    cp $dir/config-pim/file_mgen_source_22 /var/lib/lxc/$(printf "PC%02d" $i)/rootfs/home/mgen
    cp $dir/config-pim/file_mgen_source_33 /var/lib/lxc/$(printf "PC%02d" $i)/rootfs/home/mgen
done

$dir/scripts/09-start-pim $num_routers $dir/config-pim 2>&1

for ((i=1; i<=$routers; i++)); do 
    var=$(lxc-info -n $(printf "R%02d" $i) | grep State: | awk '{print $2}')
    if [ $var == "RUNNING" ]; then
    array_test=()
    for iface in $(lxc-attach -n $(printf "R%02d" $i) -- bash -c "ifconfig | cut -d ' ' -f1| tr ':' '\n' | awk NF")
    do  if [[ ("$iface" != "lo") && ("$iface" != "pimreg") ]]; then 
            array_test+=("$iface")
        fi
    done
    for j in "${array_test[@]}"; do
        10-source-mgen $(printf "R%02d" $i) $j > /dev/null
    done  
    fi
done
for ((i=1; i<=$pcs; i++)); do 
    var=$(lxc-info -n $(printf "PC%02d" $i) | grep State: | awk '{print $2}')
    if [ $var == "RUNNING" ]; then
    array_test=()
    for iface in $(lxc-attach -n $(printf "PC%02d" $i) -- bash -c "ifconfig | cut -d ' ' -f1| tr ':' '\n' | awk NF")
    do  if [ "$iface" != "lo" ]; then 
            array_test+=("$iface")
        fi
    done
    for j in "${array_test[@]}"; do
        10-source-mgen $(printf "PC%02d" $i) $j > /dev/null
    done 
    fi
done



